services:
  - type: web
    name: Stay Calendar
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:7lmfb33StfqM21HQJUdtpJD6SK/UP+3aqc/4I03pffQ=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://stay-calendar.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file