services:
  - type: web
    name: Stay Calendar
    env: php
    buildCommand: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 18
      nvm use 18
      composer install --optimize-autoloader --no-dev
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:7lmfb33StfqM21HQJUdtpJD6SK/UP+3aqc/4I03pffQ=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://stay-calendar.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file